- name: install nginx
  hosts: web
  become: yes
  tasks: #install nginx
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the service
    ansible.builtin.service:
      name: nginx
      state: started
  -name: enable the service
  ansible
